# docker-compose.yml
version: "3"
services:
  labpro-backend-prod:
    container_name: labpro-backend-prod
    volumes:
      - ../../:/app:z
    build:
      context: ../../
      dockerfile: builds/server-prod/Dockerfile
    env_file: ../../builds/server-prod/.env
    ports:
      - 8080:8080
    networks:
      - dbconnect
    depends_on:
      - mariadb
    restart: :
      - on-failure
  mariadb:
     image: mariadb:10.3
    container_name: labpro-database-prod
    env_file: ../../builds/database-prod/.env
    ports:
      - 3307:3306
    networks:
      - dbconnect
networks:
  dbconnect:
    driver: bridge
