# docker-compose.yml
version: "3"
services:
  labpro-backend-dev:
    container_name: labpro-backend-dev
    volumes:
      - ../../:/app:z
    build:
      context: ../../
      dockerfile: builds/server/Dockerfile
    env_file: ../../builds/server/.env
    ports:
      - 8080:8080
    networks:
      - dbconnect
    depends_on:
      - mariadb-labpro
  mariadb-labpro:
    container_name: labpro-database-dev
    image: mariadb:10.3
    env_file: ../../builds/database/.env
    ports:
      - 3307:3306
    networks:
      - dbconnect
networks:
  dbconnect:
    driver: bridge
